config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get  '/upload_file(.:format)' , to: 'upload#index'
  post '/upload_file(.:format)' , to: 'upload#uploadFile'
 
  get  '/mainpage' , to: 'mainpage#index' , as: 'index_mainpage'

  get  '/userinfo/:email' , to: 'userpage#show_another'  , as: 'show_another_user'
  get  '/userinfo' , to: 'userpage#show'  , as: 'show_user'
  get  '/userinfo/info/:id' , to: 'userpage#info' , as: 'info_user'

  get  '/questions', to: 'question#index' , as: 'index_question'
  get  '/questions/new', to: 'question#create' , as: 'create_question'     
  post '/questions/new(.:format)', to: 'question#new' , as: 'new_question'
  get  '/questions/show/:id(.:format)', to: 'question#show' , as: 'question'
  post '/questions/show/:id(.:format)', to: 'comment#new' , as: 'new_comment'

  get '/star/question/:id', to: 'star#star_question' , as: 'star_question'
  get '/star/comment/:id' , to: 'star#star_comment'  , as: 'star_comment'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are: xjt
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def new
		@comment=Comment.new(comments_params)
		@comment.save
		@question=Question.find(params[:id])
		redirect_to @question
	end

	private
		def comments_params
			params.require(:comment).permit(:question_id, :content, :commenter, :reply_to)
		end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	def index
		@user = current_user
	end


end

app/controllers/mainpage_controller.rb
class MainpageController < ApplicationController
	def index
		
	end
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
	before_action :authenticate_user!
	def index
		@user = current_user
		@questions= Question.all
		@populars= Question.limit(5).all.order(stars: :desc)
	end

	def show
		@reply_to
		@user=current_user
		@question=Question.find(params[:id])
		#@question=Question.find(all,:conditions => [asker = ss])
		@comments=Comment.where(question_id: params[:id])
	end

	def create
		@user=current_user
	end

	def new
		@question=Question.new(question_params)
		@question.save
		@user=current_user
		@user.question_num += 1
		@user.save
		redirect_to @question
	end

	private
		def question_params
			params.require(:question).permit(:title, :content, :asker)
		end
end

app/controllers/star_controller.rb
class StarController < ApplicationController
	def star_question
		@user=current_user
		@question=Question.find_by(:id => params[:question])
		if not @question.stars_list.include? @user.email
			@question.stars_list.insert(-1," "+@user.email)
			@question.stars += 1
		end
		@question.save
		redirect_to @question
	end

	def star_comment
		@comment=Comment.find_by(:id => params[:comment])
		@comment.stars += 1
		@comment.save
		@question=Question.find_by(:id => params[:id])
		redirect_to @question
	end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
	def index
<<<<<<< HEAD
		# This array save user's projects'name with id
		#store project's branches
		#@projectsFileTree = Array.new
		#@projectsId.each do |id|
		#	request = Typhoeus::Request.new(
		#		"http://120.27.22.10/api/v4/projects/#{id}/repository/tree",
		#		method: :get,
		#		params: {
		#				  private_token: "1AgYdoJ8Faf2Z6ExXX1i",
		#				  #recursive: "true"
		#				}
		#	)
		#	request.run
		#	response = request.response
		#	@projectsFileTree.push(JSON.parse(response.body))
		#	#logger.debug(response.body)
		#end

		#@projectFileTree = Array.new
		#@projectsFileTree.each do |t|
		#	logger.debug(t)
		#	tt = Hash.new
		#	tt = JSON.parse(t)
		#	singleProject = Array.new
		#	tt.each do |ttt|
		#		singleProject.push(JSON.parse(tt))
		#	end
		#	@projectFileTree.push(singleProject)
		#end
		#logger.debug(@projectFileTree)


=======
>>>>>>> d25e94549b58e5e31cae3033878325bfb8337043
	end

	def uploadFile
		logger.debug("File:")
		@theUploadFile = params[:uploadFile]
		logger.debug(params[:uploadFile])
		logger.debug(@theUploadFile["fileTitle"])
		logger.debug(params[:fileContent])
	end

	def showProjectFiles
		logger.debug("To show your Files +++++++++++++++++++")
	end


end

app/controllers/userpage_controller.rb
class UserpageController < ApplicationController
	before_action :authenticate_user!
	def show
		@user=current_user
		@questions=Question.where(asker: @user.email)
		@comments=Comment.where(commenter: @user.email)
	end

	def info
		@user=current_user
	end

	def show_another
		@user=current_user
		@user_by_email=User.find_by(:email => (params[:email]+".com") )
		@questions=Question.where(asker: @user_by_email.email)
		@comments=Comment.where(commenter: @user_by_email.email)
	end 

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/star_helper.rb
module StarHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/userpage_helper.rb
module UserpageHelper
end

app/views/home/index.html.erb
<head>
	<style type="text/css">
		.main{
			width:960px;
			margin:0 auto;
		}
		.header{
			display:flex;
			justify-content: space-between;
			background-color:#66CCFF;
			line-height: 40px;
			margin-bottom: 40px;
		}
		.h-box{
			padding:0 20px;
		}
		.section{
			display:flex;
			justify-content: space-around;
		}
		.flex1{
			flex:1;
			text-align: center;
			line-height:150px;
			border:5px solid #fff;
			background-color: #eee;
		}
	</style>
</head>
<body>
	<div class="main">
		<div class="header">
			<div class="h-box">
  				<strong>The current user is:</strong>
  					<%= link_to @user.email , show_user_path %>
  			</div>
  			<div class="h-box">
 				<%= link_to "Log out" , destroy_user_session_path, :method => :delete %>
			</div>
		</div>

		<div class="section">
			<div class="flex1">
				<%= link_to "This is the question list" , index_question_path %>
			</div>

			<div class="flex1">
				<%= link_to "This is the ask page" , create_question_path %>
			</div>
		</div>
	</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Begin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  


  <body>
    <%= yield %>
  </body>
</html>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/mainpage/index.html.erb
<h1>Here is mainpage</h1>
<p>
	<%= link_to "Log out" , destroy_user_session_path, :method => :delete %>
</p>

app/views/question/create.html.erb
<head>
  <style type="text/css">
    .main {
      width: 960px;
      margin: 0 auto;
    }
    .header{
      display:flex;
      justify-content: space-between;
      background-color:#66CCFF;
      line-height: 40px;
      margin-bottom: 40px;
    }
    .h-box{
      padding:0 20px;
    }
    .input-width-max > input {
      width: 100%;
      background-color:#efefef;
    }

    .textarea-width-max > textarea {
      width: 100%;
    }

    .textarea-height-400 > textarea {
      height: 400px;
      background-color: #efefef;
    }

    .submit-button > input {
      display: block;
      width: 400px;
      height: 40px;
      background-color: blue;
      font-size: 24px;
      color: white;
      margin: 0 auto;
    }

    .text-center {
      text-align: center;
    }

    .font-bold {
      font-weight: bold;
    }

    .f-22 {
      font-size: 22px;
    }
  </style>
</head>
<body>
<div class="main">
<div class="header">
  <div class="h-box">
    <strong>
      <%= link_to '首页' , root_path %>
    </strong>
  </div>
  <div class="h-box">
    <strong>The current user is:</strong>
    <%= link_to @user.email , show_user_path %>
  </div>
  <div class="h-box">
    <%= link_to "Log out" , destroy_user_session_path, :method => :delete %>  
  </div>
</div>

<div class="section">
  
    <h1 class="text-center font-bold">写下你的问题</h1>
    <p class="text-center f-22">描述精确的问题更容易得到解答</p>
    <% @user = current_user %>
    <%= form_for :question do |f| %>
      <%= f.label :title %>
      <div class="input-width-max">
        <%= f.text_field :title %>
      </div>
      <p>
        <%= f.label :content %><br>
      <div class="textarea-width-max textarea-height-400">
        <%= f.text_area :content %>
      </div>
      </p>
      <%= f.hidden_field :asker, :value => @user.email %>
      <div class="submit-button">
        <%= f.submit :提交问题 %>
      </div>
    <% end %>
  </div>
</div>



</body>

app/views/question/index.html.erb
<head>
  <style type="text/css">
    .main {
      width: 960px;
      margin: 0 auto;
    }
    .header{
      display:flex;
      justify-content: space-between;
      background-color:#66CCFF;
      line-height: 40px;
      margin-bottom: 40px;
    }
    .h-box{
      padding:0 20px;
    }
    .popular-box {
      width: 100%;
      border: 1px solid #efefef;
      background-color: #efefef;
      margin-bottom: 5px;
      box-shadow: 5px 5px 5px #999;
      padding-left: 50px;
      cursor: pointer;
    }
    .question-box {
      width: 100%;
      border: 1px solid #efefef;
      background-color: #eff;
      margin-bottom: 5px;
      box-shadow: 5px 5px 5px #999;
      padding-left: 50px;
      cursor: pointer;
    }
    .popular-title {
      font-size: 24px;
      font-weight: bold;
      line-height:40px;
    }

    .popular-asker {
      padding-left: 30px;
    }
  </style>
</head>
<body>
<div class="main">

<div class="header">
  <div class="h-box">
    <strong>
      <%= link_to '首页' , root_path %>
    </strong>
  </div>

  <div class="h-box">
    <strong>The current user is:</strong>
    <%= link_to @user.email , show_user_path %>
  </div>
  
  <div class="h-box">
    <%= link_to "Log out" , destroy_user_session_path, :method => :delete %>  
  </div>
</div>


  <h1>Here is question page</h1>
  <% @populars.each do |t| %>
    <div class="popular-box">
      
      <div class="popular-title">
        <!-- <%= t.title %> -->
        <%= link_to t.title, t %>
      </div>

      <div class="popular-asker">
        提问者：
        <%= t.asker %>
        &nbsp;
        赞:
        <%= t.stars %>
      </div>

      <!-- <%= link_to 'show this question', t %> -->
    </div>

  <% end %>
  <br><hr><br>
  <% @questions.each do |t| %>
    <div class="question-box">
      
      <div class="popular-title">
        <!-- <%= t.title %> -->
        <%= link_to t.title, t %>
      </div>

      <div class="popular-asker">
        提问者：
        <%= t.asker %>
        &nbsp;
        赞:
        <%= t.stars %>
      </div>

      <!-- <%= link_to 'show this question', t %> -->
    </div>

  <% end %>
</div>

<!-- <table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Asker</th>
  </tr>

  <% @questions.each do |t| %>
    <tr>
      <td><%= t.title %></td>
      <td><%= t.content %></td>
      <td><%= t.asker %></td>
      <td><%= link_to 'show this question', t %></td>
    </tr>
  <% end %>
</table> -->





</body>

app/views/question/show.html.erb
<head>
	<style type="text/css">
		.main{
			width:960px;
			margin:0 auto;
		}
		.header{
			display:flex;
			justify-content: space-between;
			background-color:#66CCFF;
			line-height: 40px;
			margin-bottom: 40px;
		}
		.h-box{
			padding:0 20px;
		}
		.top{
			display: flex;
			justify-content: space-between;
		}
		.title{
			font-size:22px;
			font-weight: bold;
			margin-bottom: 40px;
		}
		.right{
			text-align: right;
			margin-bottom: 40px;
		}
		.comment-title{
			font-size: 20px;
			font-weight:bold;
			margin-bottom:10px;
			padding-left: 20px;
		}
		.comment-area>textarea{
			width:960px;
			height:60px;
			background-color: #efefef;
		}
		.comments-box{
			background-color: #eee;
			padding:20px;
			margin-bottom: 20px;
		}
		.comment-msg{
			text-align: right;
			margin-top:10px;
		}
		.reee{
			display:none;
		}
		.re-content>textarea{
			width:920px;
		}
	</style>
</head>
<body>
<div class="main">

<div class="header">
	<div class="h-box">
	    <strong>
	      <%= link_to '首页' , root_path %>
	    </strong>
	  </div>
	<div class="h-box">
	  <strong>The current user is:</strong>
	  <%= link_to @user.email , show_user_path %>
	</div>
  	<div class="h-box">
  		<%= link_to "Log out" , destroy_user_session_path, :method => :delete %>
	</div>
</div>

<div>


	<div class="top">
		<div class="title h-box">
			<%= @question.title %>
		</div>
		<div class="asker h-box">
			<%= link_to "提问者:#{@question.asker}" , show_another_user_path(:email => @question.asker) %>
		</div>
	</div>
	<div class="content">
		<%= @question.content %>
	</div>
	<div class="right">
		☆:<%= @question.stars %>
		&nbsp;&nbsp;&nbsp;
		<%= link_to 'Star!' , star_question_path(:question => @question.id) %>
	</div>

	<%= form_for :comment do |f| %>
		<div class="comment-title">
			我来回答
		</div>
		<div class="comment-area">
			<%= f.text_area :content %>
		</div>
		<%= f.hidden_field :question_id, :value => params[:id] %>
  		<%= f.hidden_field :reply_to, :value => @reply_to %>
  		<%= f.hidden_field :commenter, :value => @user.email %>
		<div class="right">
			<%= f.submit :发布%>
		</div>
	<% end %>

	<% @comments.each do |t| %>
		<div class="comments-box">
			<div>
				<%= t.content %>
			</div>
			<div class="comment-msg">
				发表者:<%= t.commenter %>&nbsp;&nbsp;&nbsp;
				<% if t.reply_to != '' %>
					回复:
				<% end %>
				<%= t.reply_to %>&nbsp;&nbsp;&nbsp;
				☆:<%= t.stars %>&nbsp;&nbsp;&nbsp;
				<%= link_to 'Star!' , star_comment_path(:comment => t.id) %>
				<button class="buttons" onclick="ree(this)">
					回复
				</button>
			</div>
			<div class="reee">
				<%= form_for :comment do |f| %>
					<div class="re-content">
						<%= f.text_area :content %>
					</div>
					<%= f.hidden_field :question_id, :value => params[:id] %>
	  				<%= f.hidden_field :reply_to, :value => t.commenter %>
	  				<%= f.hidden_field :commenter, :value => @user.email %>
					<div class="comment-msg">
						<%= f.submit :回复 %>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>
<!--
<table>
	<tr>
		<th>Title</th>
		<th>Content</th>
		<th>Asker</th>
	</tr>

	<tr>
		<td><%= @question.title %></td>
		<td><%= @question.content %></td>
		<td><%= @question.asker %></td>
		<td><%= @question.stars %></td>
		<td><%= link_to 'Star!' , star_question_path(:question => @question.id) %>
	</tr>

	<tr>
		<td><strong>Comment</strong></td>
	</tr>

	<tr>
		<th>Commenter</th>
		<th>Reply</th>
		<th>Content</th>
		<th>Starts</th>
	</tr>

	<% @comments.each do |t| %>
	<table>
		<tr>
			<td><%= t.commenter %></td>
			<td><%= t.reply_to %></td>
			<td><%= t.content %></td>
			<td><%= t.stars %></td>
			<td><%= link_to 'Star!' , star_comment_path(:comment => t.id) %></td>

		</tr>

		<tr>
			<%= form_for :comment do |f| %>
				<p>
					<%= f.label :reply %>
					<%= f.text_area :content %>
				</p>
				<%= f.hidden_field :question_id, :value => params[:id] %>
  				<%= f.hidden_field :reply_to, :value => t.commenter %>
  				<%= f.hidden_field :commenter, :value => @user.email %>
  				
				<p>
					<%= f.submit :回复 %>
				</p>
			<% end %>
		</tr>

	<%end%>
	</table>

</table>


<%= form_for :comment do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  	<%= f.hidden_field :question_id, :value => params[:id] %>
  	<%= f.hidden_field :reply_to, :value => @reply_to %>
  	<%= f.hidden_field :commenter, :value => @user.email %>


  <p>
    <%= f.submit :发布%>
  </p>


  <p>
	<%= link_to "Log out" , destroy_user_session_path, :method => :delete %>
</p>


<% end %>
-->
</div>
<script type="text/javascript">
	var rebox = document.getElementsByClassName("reee")
	var btns = document.getElementsByClassName("buttons")
	var showshow = function(i){
		btns[i].onclick = function(){
			console.log(i);
			rebox[i].style.display = "block";
		}
	}
	for(var i=0;i<btns.length;i++){
		showshow(i);
	}
</script>
</body>

app/views/upload/index.html.erb
<h1>Welcome you gays</h1>
<h2>This is your projects:</h2>


<%= form_for :uploadFile, url: {:action => "uploadFile"} do |f| %>
	<div>
		<%= f.label "Input your title:" %>
		<%= f.text_field :fileTitle , :size => 20 %>
	</div>

	<div>
		<%= f.label "Input your file content:" %>
		<%= f.text_area :fileContent , :rows => 20 ,:cols => 15 %>
	</div>
	<%= f.submit "Upload your file" %>
<% end %>

app/views/upload/uploadFile.html.erb
<h1>Done</h1>

app/views/userpage/info.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

app/views/userpage/show.html.erb
<head>
  <style type="text/css">
    .main {
      width: 960px;
      margin: 0 auto;
    }
    .header{
      display:flex;
      justify-content: space-between;
      background-color:#66CCFF;
      line-height: 40px;
      margin-bottom: 40px;
    }
    .h-box{
      padding:0 20px;
    }
    .box{
      background-color: #eee;
      padding:20px;
      margin-bottom: 20px;
    }
    .questions{
      float:left;
      width: 49%;
      border: 1px;
      padding: 10px;
    }
    .question-stars{
      float:right;
    }
    .comments{
      float:right;
      width: 49%;
      border: 1px;
      padding: 10px;
    }
    .comment-stars{
      float:right;
    }
  </style>
</head>


<div class="main">

	<div class="header">
		<div class="h-box">
    		<strong>
      			<%= link_to '首页' , root_path %>
    		</strong>
  		</div>

		<div class="h-box">
		  	<strong>The current user is:</strong>
		 	<%= link_to @user.email , show_user_path %>
	    </div>
	  	<div class="h-box">
	  		<%= link_to "Log out" , destroy_user_session_path, :method => :delete %>
		</div>
	</div>


<div class="body">

  <div class="questions">
  	<p>You have asked: <strong><%= @questions.count %></strong> questions already!</p>
  	<p>Here are your questions:</p>
  	<% @questions.each do |t| %>
        <div class="box">
  	  	  <%= link_to t.title , t%>
            <div class="question-stars" >
              ☆:<%= t.stars %>
            </div>
        </div>
	  <% end %>
  </div>


  <div class="comments">
	  <p>You have commented: <strong><%= @comments.count %></strong> comments already!</p>
	  <p>Here are your comments:</p>
	  <% @comments.each do |t| %>
      <div class="box">
		    <%= link_to t.content , question_path(:id => t.question_id) %>
        <div class="comment-stars" >
            ☆:<%= t.stars %>
        </div>
      </div>
	  <% end %>
  </div>


</div>

</div>

app/views/userpage/show_another.html.erb
<head>
  <style type="text/css">
    .main {
      width: 960px;
      margin: 0 auto;
    }
    .header{
      display:flex;
      justify-content: space-between;
      background-color:#66CCFF;
      line-height: 40px;
      margin-bottom: 40px;
    }
    .h-box{
      padding:0 20px;
    }
    .box{
      background-color: #eee;
      padding:20px;
      margin-bottom: 20px;
    }
    .questions{
      float:left;
      width: 49%;
      border: 1px;
      padding: 10px;
    }
    .comments{
      float:right;
      width: 49%;
      border: 1px;
      padding: 10px;
    }
  </style>
</head>

<body>
<div class="main">

	<div class="header">
		<div class="h-box">
    		<strong>
      			<%= link_to '首页' , root_path %>
    		</strong>
  		</div>

		<div class="h-box">
		  	<strong>The current user is:</strong>
		 	<%= link_to @user.email , show_user_path %>
	    </div>
	  	<div class="h-box">
	  		<%= link_to "Log out" , destroy_user_session_path, :method => :delete %>
		</div>
	</div>


<p>This is <strong><%= @user_by_email.email %></strong> 's information page: </p>
<div>
  <div  class="questions">
      <p>He/She has asked: <strong><%= @questions.count %></strong> questions already!</p>
	    <p>Here are his/her questions:</p>
	    <% @questions.each do |t| %>
        <div class="box">
	  	    <p><%= link_to t.title , t%></p>
        </div>
	    <% end %>
  </div>

  <div class="comments">
	  <p>He/She has commented: <strong><%= @comments.count %></strong> comments already!</p>
	  <p>Here are his/her comments:</p>
	  <% @comments.each do |t| %>
      <div class="box">
		    <p><%= link_to t.content , question_path(:id => t.question_id)%></p>
      </div>
	  <% end %>
  </div>
</div>
</div>
</body>